Capstone.Web/Controllers/HomeController.cs
using Capstone.Web.DataAccess;
using Capstone.Web.Models;
using log4net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Capstone.Web.Controllers
{
    public class HomeController : Controller
    {
        //creating an instance of the logger
        //Use LogManager.GetLogger(typeof(CLASSNAME))
        private ILog logger = LogManager.GetLogger(typeof(HomeController));
        private IParksDAL parksDAL;

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            if (parksDAL == null)
            {
                string fileName = Server.MapPath("~/App_Data/Parks.tsv");
                parksDAL = new ParksFileDAL(fileName);
            }
        }


        // GET: Home
        public ActionResult Index()
        {            
            List<Park> allParks = parksDAL.GetAllParks();

            logger.Debug("Entering index method");
            return View(allParks);
        }
    }
}

Capstone.Web/Controllers/ParksController.cs
using Capstone.Web.DataAccess;
using Capstone.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;


namespace Capstone.Web.Controllers
{
    public class ParksController : Controller
    {

        private IParksDAL parkDAL;

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            if (parkDAL == null)
            {
                string fileName = Server.MapPath("~/App_Data/Parks.tsv");
                parkDAL = new ParksFileDAL(fileName);
            }
        }

        public ParksController()
        {

        }
        
        public ParksController(IParksDAL dal)
        {
            parkDAL = dal;
        }

        public ActionResult Detail(string id)
        {
            Park p = parkDAL.GetPark(id);

            return View(p);
        }


    }
}

Capstone.Web/Views/Home/Index.cshtml
@model List<Capstone.Web.Models.Park>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="title">Our National Park System</h2>


<p class="infoParagraph">A national park is a park in use for conservation purposes. Often it is a reserve of natural, semi-natural, or developed land that a sovereign state declares or owns. Although individual nations designate their own national parks differently, there is a common idea: the conservation of 'wild nature' for posterity and as a symbol of national pride. National parks are almost always open to visitors. Most national parks provide outdoor recreation and camping opportunities as well as classes designed to educate the public on the importance of conservation and the natural wonders of the land in which the national park is located.</p>

@foreach(var park in Model)
{ 
<div class="divColumns">
    <a href="@Url.Action("Detail", "Parks", new { id = park.ParkCode})"><img src="~/Content/img/parks/@park.ImageFile" alt=@park.ParkName /></a>
        <h3>@park.ParkName</h3>
        <h4>@park.State</h4>
</div>
}