Capstone.Web/Controllers/WeatherController.cs
using Capstone.Web.DataAccess;
using Capstone.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Capstone.Web.Controllers
{
    public class WeatherController : Controller
    {
        private IWeatherDAL weatherDAL;

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            if (weatherDAL == null)
            {
                string fileName = Server.MapPath("~/App_Data/Weather.tsv");
                weatherDAL = new WeatherFileDAL(fileName);
            }
        }

        public WeatherController()
        {

        }

        public WeatherController(IWeatherDAL dal)
        {
            weatherDAL = dal;
        }

        public ActionResult Detail(string id)
        {
            List<DailyForecast> df = weatherDAL.Get5DayForecast(id);

            return View(df);
        }

        public ActionResult Celcius(string id)
        {
            List<DailyForecast> df = weatherDAL.Get5DayForecast(id);

            return View(df);
        }
    }
}

Capstone.Web/Views/Weather/Celcius.cshtml
@model List<Capstone.Web.Models.DailyForecast>

@{
    ViewBag.Title = "Celcius";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Five Day Forecast</h2>


<section class="weather5day">

    @foreach (var df in Model)
    { <section class="weatherOneDay">
        <p>Day @df.DayNumber</p>
        <img src="@df.WeatherImgFile" />
        <p>@df.Forecast</p>
        <p class="highTemp">High: @df.CelciusHigh &deg; C</p>
        <p>Low: @df.CelciusLow &deg; C</p>
        <p>@df.ForecastAdvice</p>
        <p>@df.TempAdvice</p>
    </section>
    }
</section>

Capstone.Web/Views/Weather/Detail.cshtml
@model List<Capstone.Web.Models.DailyForecast>

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Five Day Forecast</h2>


@Html.ActionLink("Prefer to view in celcius?", "Celcius", "Weather", new { id = Model[0].ParkCode}, new {@class = "weatherLink"} )

<section class="weather5day">

    @foreach (var df in Model)
    { <section class="weatherOneDay">
        <p>Day @df.DayNumber</p>
        <img src="@df.WeatherImgFile" />
        <p>@df.Forecast</p>
        <p class="highTemp">High: @df.HighTemperature &deg; F</p>
        <p>Low: @df.LowTemperature &deg; F</p>
        <p>@df.ForecastAdvice</p>
        <p>@df.TempAdvice</p>
    </section>
    }
</section>