Capstone.Web/Controllers/SurveyController.cs
using Capstone.Web.DataAccess;
using Capstone.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Capstone.Web.Controllers
{
    public class SurveyController : Controller
    {

        string Session_Key;
        SurveyResults results = new SurveyResults();

        private ISurveyDAL surveyDAL;

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            if (surveyDAL == null)
            {
                string fileName = Server.MapPath("~/App_Data/Survey_Results.tsv");
                surveyDAL = new SurveyFileDAL(fileName);
            }
        }

        public SurveyController()
        {

        }

        public SurveyController(ISurveyDAL dal)
        {
            surveyDAL = dal;
        }

        [HttpGet]
        public ActionResult Create()
        {
            //if SessionID exists, return view for results.  If not, return Create view
            if (Session[Session_Key] != null)
            {               
                return RedirectToAction("Results");
            }
            else
            {
                Session[Session_Key] = "xyz";
                return View();
            }
            
        }

        [HttpPost]
        public ActionResult Create(string parkCode)
        {
            surveyDAL.WriteResultToFile(parkCode);
            return RedirectToAction("Results");
        }

        public ActionResult Results()
        {
            Dictionary<string, int> resultsDictionary = surveyDAL.ReadInResults();

            results.Results = resultsDictionary;
            
            return View(results);
        }

    }
}

Capstone.Web/Views/Survey/Create.cshtml
@model Capstone.Web.Models.Park
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h3 class="title">Take the survey and be counted!</h3>

<p class="surveyParagraph">Which park is <em>your</em> favorite?</p>

@using (Html.BeginForm("Create", "Survey", FormMethod.Post))
{
    <div class="surveyChoices">
        @Html.RadioButton("ParkCode", "GNP") Glacier National Park <br />
        @Html.RadioButton("ParkCode", "GCNP") Grand Canyon National Park <br />
        @Html.RadioButton("ParkCode", "GTNP") Grand Teton National Park <br />
        @Html.RadioButton("ParkCode", "MRNP") Mount Rainier National Park <br />
        @Html.RadioButton("ParkCode", "GSMNP") Great Smoky Mountains National Park <br />
        @Html.RadioButton("ParkCode", "ENP") Everglades National Park <br />
        @Html.RadioButton("ParkCode", "YNP") Yellowstone National Park <br />
        @Html.RadioButton("ParkCode", "YNP2") Yosemite National Park <br />
        @Html.RadioButton("ParkCode", "CVNP") Cuyahoga Valley National Park <br />
        @Html.RadioButton("ParkCode", "RMNP") Rocky Mountain National Park <br />


        <button>VOTE!</button>
    </div>
}

Capstone.Web/Views/Survey/Results.cshtml
@model Capstone.Web.Models.SurveyResults
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thanks for your vote! Come back tomorrow to vote again!</h2>

<table class="resultsTable">
    @foreach (KeyValuePair<string, int> kvp in Model.Results)
    {
        <tr>
        @if (kvp.Key == "GNP")
        {
            <td class="resultsData">Glacier National Park</td>
        }
        else if (kvp.Key == "GCNP")
        {
            <td class="resultsData">Grand Canyon National Park</td>
        }
        else if (@kvp.Key == "GTNP")
        {
            <td class="resultsData">Grand Teton National Park</td>
        }
        else if (@kvp.Key == "MRNP")
        {
            <td class="resultsData">Mount Rainier National Park</td>
        }
        else if (@kvp.Key == "GSMNP")
        {
            <td class="resultsData">Great Smoky Mountains National Park</td>
        }
        else if (@kvp.Key == "ENP")
        {
            <td class="resultsData">Everglades National Park</td>
        }
        else if (@kvp.Key == "YNP")
        {
            <td class="resultsData">Yellowstone National Park</td>
        }
        else if (@kvp.Key == "YNP2")
        {
            <td class="resultsData">Yosemite National Park</td>
        }
        else if (@kvp.Key == "CVNP")
        {
            <td class="resultsData">Cuyahoga Valley National Park</td>
        }
        else
        {
            <td class="resultsData">Rocky Mountain National Park</td>
        }
        <td class="resultsData">Vote Count: @kvp.Value</td>
        </tr>
    }
    </table>
    